/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetAccessCreate
 */
export interface AssetAccessCreate {
    /**
     * 
     * @type {string}
     * @memberof AssetAccessCreate
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof AssetAccessCreate
     */
    role: AssetAccessCreateRoleEnum;
}


/**
 * @export
 */
export const AssetAccessCreateRoleEnum = {
    Viewer: 'VIEWER',
    Editor: 'EDITOR',
    Admin: 'ADMIN'
} as const;
export type AssetAccessCreateRoleEnum = typeof AssetAccessCreateRoleEnum[keyof typeof AssetAccessCreateRoleEnum];


/**
 * Check if a given object implements the AssetAccessCreate interface.
 */
export function instanceOfAssetAccessCreate(value: object): value is AssetAccessCreate {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function AssetAccessCreateFromJSON(json: any): AssetAccessCreate {
    return AssetAccessCreateFromJSONTyped(json, false);
}

export function AssetAccessCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetAccessCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'role': json['role'],
    };
}

export function AssetAccessCreateToJSON(json: any): AssetAccessCreate {
    return AssetAccessCreateToJSONTyped(json, false);
}

export function AssetAccessCreateToJSONTyped(value?: AssetAccessCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'role': value['role'],
    };
}

