/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetAccessRemove
 */
export interface AssetAccessRemove {
    /**
     * 
     * @type {string}
     * @memberof AssetAccessRemove
     */
    userId: string;
}

/**
 * Check if a given object implements the AssetAccessRemove interface.
 */
export function instanceOfAssetAccessRemove(value: object): value is AssetAccessRemove {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AssetAccessRemoveFromJSON(json: any): AssetAccessRemove {
    return AssetAccessRemoveFromJSONTyped(json, false);
}

export function AssetAccessRemoveFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetAccessRemove {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function AssetAccessRemoveToJSON(json: any): AssetAccessRemove {
    return AssetAccessRemoveToJSONTyped(json, false);
}

export function AssetAccessRemoveToJSONTyped(value?: AssetAccessRemove | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

