/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetUpdate
 */
export interface AssetUpdate {
    /**
     * 
     * @type {string}
     * @memberof AssetUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetUpdate
     */
    description?: string;
}

/**
 * Check if a given object implements the AssetUpdate interface.
 */
export function instanceOfAssetUpdate(value: object): value is AssetUpdate {
    return true;
}

export function AssetUpdateFromJSON(json: any): AssetUpdate {
    return AssetUpdateFromJSONTyped(json, false);
}

export function AssetUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AssetUpdateToJSON(json: any): AssetUpdate {
    return AssetUpdateToJSONTyped(json, false);
}

export function AssetUpdateToJSONTyped(value?: AssetUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

