/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetCreate
 */
export interface AssetCreate {
    /**
     * 
     * @type {string}
     * @memberof AssetCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AssetCreate
     */
    description?: string;
}

/**
 * Check if a given object implements the AssetCreate interface.
 */
export function instanceOfAssetCreate(value: object): value is AssetCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AssetCreateFromJSON(json: any): AssetCreate {
    return AssetCreateFromJSONTyped(json, false);
}

export function AssetCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AssetCreateToJSON(json: any): AssetCreate {
    return AssetCreateToJSONTyped(json, false);
}

export function AssetCreateToJSONTyped(value?: AssetCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

