/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetUpdate
 */
export interface AssetUpdate {
    /**
     * 
     * @type {string}
     * @memberof AssetUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetUpdate
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AssetUpdate
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AssetUpdate
     */
    kind?: AssetUpdateKindEnum;
    /**
     * 
     * @type {string}
     * @memberof AssetUpdate
     */
    sourceTemplateId?: string;
}


/**
 * @export
 */
export const AssetUpdateKindEnum = {
    Regular: 'REGULAR',
    Template: 'TEMPLATE'
} as const;
export type AssetUpdateKindEnum = typeof AssetUpdateKindEnum[keyof typeof AssetUpdateKindEnum];


/**
 * Check if a given object implements the AssetUpdate interface.
 */
export function instanceOfAssetUpdate(value: object): value is AssetUpdate {
    return true;
}

export function AssetUpdateFromJSON(json: any): AssetUpdate {
    return AssetUpdateFromJSONTyped(json, false);
}

export function AssetUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'sourceTemplateId': json['sourceTemplateId'] == null ? undefined : json['sourceTemplateId'],
    };
}

export function AssetUpdateToJSON(json: any): AssetUpdate {
    return AssetUpdateToJSONTyped(json, false);
}

export function AssetUpdateToJSONTyped(value?: AssetUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'isPublic': value['isPublic'],
        'kind': value['kind'],
        'sourceTemplateId': value['sourceTemplateId'],
    };
}

