/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardCreate
 */
export interface CardCreate {
    /**
     * 
     * @type {string}
     * @memberof CardCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CardCreate
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof CardCreate
     */
    order?: number;
}

/**
 * Check if a given object implements the CardCreate interface.
 */
export function instanceOfCardCreate(value: object): value is CardCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CardCreateFromJSON(json: any): CardCreate {
    return CardCreateFromJSONTyped(json, false);
}

export function CardCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function CardCreateToJSON(json: any): CardCreate {
    return CardCreateToJSONTyped(json, false);
}

export function CardCreateToJSONTyped(value?: CardCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'order': value['order'],
    };
}

