/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardUpdate
 */
export interface CardUpdate {
    /**
     * 
     * @type {string}
     * @memberof CardUpdate
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CardUpdate
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof CardUpdate
     */
    order?: number;
}

/**
 * Check if a given object implements the CardUpdate interface.
 */
export function instanceOfCardUpdate(value: object): value is CardUpdate {
    return true;
}

export function CardUpdateFromJSON(json: any): CardUpdate {
    return CardUpdateFromJSONTyped(json, false);
}

export function CardUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function CardUpdateToJSON(json: any): CardUpdate {
    return CardUpdateToJSONTyped(json, false);
}

export function CardUpdateToJSONTyped(value?: CardUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'order': value['order'],
    };
}

