/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Chunk
 */
export interface Chunk {
    /**
     * 
     * @type {string}
     * @memberof Chunk
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Chunk
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof Chunk
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof Chunk
     */
    cardId?: string;
}

/**
 * Check if a given object implements the Chunk interface.
 */
export function instanceOfChunk(value: object): value is Chunk {
    return true;
}

export function ChunkFromJSON(json: any): Chunk {
    return ChunkFromJSONTyped(json, false);
}

export function ChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Chunk {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'content': json['content'] == null ? undefined : json['content'],
        'order': json['order'] == null ? undefined : json['order'],
        'cardId': json['cardId'] == null ? undefined : json['cardId'],
    };
}

export function ChunkToJSON(json: any): Chunk {
    return ChunkToJSONTyped(json, false);
}

export function ChunkToJSONTyped(value?: Chunk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'order': value['order'],
        'cardId': value['cardId'],
    };
}

