/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatrixAnalysisRequestOptions
 */
export interface MatrixAnalysisRequestOptions {
    /**
     * 
     * @type {boolean}
     * @memberof MatrixAnalysisRequestOptions
     */
    includeConfidence?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MatrixAnalysisRequestOptions
     */
    includeDetails?: boolean;
}

/**
 * Check if a given object implements the MatrixAnalysisRequestOptions interface.
 */
export function instanceOfMatrixAnalysisRequestOptions(value: object): value is MatrixAnalysisRequestOptions {
    return true;
}

export function MatrixAnalysisRequestOptionsFromJSON(json: any): MatrixAnalysisRequestOptions {
    return MatrixAnalysisRequestOptionsFromJSONTyped(json, false);
}

export function MatrixAnalysisRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatrixAnalysisRequestOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'includeConfidence': json['includeConfidence'] == null ? undefined : json['includeConfidence'],
        'includeDetails': json['includeDetails'] == null ? undefined : json['includeDetails'],
    };
}

export function MatrixAnalysisRequestOptionsToJSON(json: any): MatrixAnalysisRequestOptions {
    return MatrixAnalysisRequestOptionsToJSONTyped(json, false);
}

export function MatrixAnalysisRequestOptionsToJSONTyped(value?: MatrixAnalysisRequestOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'includeConfidence': value['includeConfidence'],
        'includeDetails': value['includeDetails'],
    };
}

