/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatrixAnalysisResultMetadata
 */
export interface MatrixAnalysisResultMetadata {
    /**
     * 
     * @type {Date}
     * @memberof MatrixAnalysisResultMetadata
     */
    computedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof MatrixAnalysisResultMetadata
     */
    totalCells?: number;
    /**
     * 
     * @type {number}
     * @memberof MatrixAnalysisResultMetadata
     */
    averageConfidence?: number;
}

/**
 * Check if a given object implements the MatrixAnalysisResultMetadata interface.
 */
export function instanceOfMatrixAnalysisResultMetadata(value: object): value is MatrixAnalysisResultMetadata {
    return true;
}

export function MatrixAnalysisResultMetadataFromJSON(json: any): MatrixAnalysisResultMetadata {
    return MatrixAnalysisResultMetadataFromJSONTyped(json, false);
}

export function MatrixAnalysisResultMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatrixAnalysisResultMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'computedAt': json['computedAt'] == null ? undefined : (new Date(json['computedAt'])),
        'totalCells': json['totalCells'] == null ? undefined : json['totalCells'],
        'averageConfidence': json['averageConfidence'] == null ? undefined : json['averageConfidence'],
    };
}

export function MatrixAnalysisResultMetadataToJSON(json: any): MatrixAnalysisResultMetadata {
    return MatrixAnalysisResultMetadataToJSONTyped(json, false);
}

export function MatrixAnalysisResultMetadataToJSONTyped(value?: MatrixAnalysisResultMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'computedAt': value['computedAt'] == null ? undefined : ((value['computedAt']).toISOString()),
        'totalCells': value['totalCells'],
        'averageConfidence': value['averageConfidence'],
    };
}

