/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatrixAnalysisRequestOptions } from './MatrixAnalysisRequestOptions';
import {
    MatrixAnalysisRequestOptionsFromJSON,
    MatrixAnalysisRequestOptionsFromJSONTyped,
    MatrixAnalysisRequestOptionsToJSON,
    MatrixAnalysisRequestOptionsToJSONTyped,
} from './MatrixAnalysisRequestOptions';

/**
 * 
 * @export
 * @interface MatrixAnalysisRequest
 */
export interface MatrixAnalysisRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof MatrixAnalysisRequest
     */
    assetIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MatrixAnalysisRequest
     */
    scenarioIds: Array<string>;
    /**
     * 
     * @type {MatrixAnalysisRequestOptions}
     * @memberof MatrixAnalysisRequest
     */
    options?: MatrixAnalysisRequestOptions;
}

/**
 * Check if a given object implements the MatrixAnalysisRequest interface.
 */
export function instanceOfMatrixAnalysisRequest(value: object): value is MatrixAnalysisRequest {
    if (!('assetIds' in value) || value['assetIds'] === undefined) return false;
    if (!('scenarioIds' in value) || value['scenarioIds'] === undefined) return false;
    return true;
}

export function MatrixAnalysisRequestFromJSON(json: any): MatrixAnalysisRequest {
    return MatrixAnalysisRequestFromJSONTyped(json, false);
}

export function MatrixAnalysisRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatrixAnalysisRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assetIds': json['assetIds'],
        'scenarioIds': json['scenarioIds'],
        'options': json['options'] == null ? undefined : MatrixAnalysisRequestOptionsFromJSON(json['options']),
    };
}

export function MatrixAnalysisRequestToJSON(json: any): MatrixAnalysisRequest {
    return MatrixAnalysisRequestToJSONTyped(json, false);
}

export function MatrixAnalysisRequestToJSONTyped(value?: MatrixAnalysisRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assetIds': value['assetIds'],
        'scenarioIds': value['scenarioIds'],
        'options': MatrixAnalysisRequestOptionsToJSON(value['options']),
    };
}

