/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatrixAnalysisRequest
 */
export interface MatrixAnalysisRequest {
    /**
     * 
     * @type {string}
     * @memberof MatrixAnalysisRequest
     */
    assetId: string;
    /**
     * 
     * @type {string}
     * @memberof MatrixAnalysisRequest
     */
    scenarioId: string;
}

/**
 * Check if a given object implements the MatrixAnalysisRequest interface.
 */
export function instanceOfMatrixAnalysisRequest(value: object): value is MatrixAnalysisRequest {
    if (!('assetId' in value) || value['assetId'] === undefined) return false;
    if (!('scenarioId' in value) || value['scenarioId'] === undefined) return false;
    return true;
}

export function MatrixAnalysisRequestFromJSON(json: any): MatrixAnalysisRequest {
    return MatrixAnalysisRequestFromJSONTyped(json, false);
}

export function MatrixAnalysisRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatrixAnalysisRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['assetId'],
        'scenarioId': json['scenarioId'],
    };
}

export function MatrixAnalysisRequestToJSON(json: any): MatrixAnalysisRequest {
    return MatrixAnalysisRequestToJSONTyped(json, false);
}

export function MatrixAnalysisRequestToJSONTyped(value?: MatrixAnalysisRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assetId': value['assetId'],
        'scenarioId': value['scenarioId'],
    };
}

