/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatrixAnalysisResultMatrixInnerInner
 */
export interface MatrixAnalysisResultMatrixInnerInner {
    /**
     * 
     * @type {string}
     * @memberof MatrixAnalysisResultMatrixInnerInner
     */
    assetId?: string;
    /**
     * 
     * @type {string}
     * @memberof MatrixAnalysisResultMatrixInnerInner
     */
    scenarioId?: string;
    /**
     * 
     * @type {number}
     * @memberof MatrixAnalysisResultMatrixInnerInner
     */
    impact?: number;
    /**
     * 
     * @type {number}
     * @memberof MatrixAnalysisResultMatrixInnerInner
     */
    confidence?: number;
    /**
     * 
     * @type {string}
     * @memberof MatrixAnalysisResultMatrixInnerInner
     */
    details?: string;
}

/**
 * Check if a given object implements the MatrixAnalysisResultMatrixInnerInner interface.
 */
export function instanceOfMatrixAnalysisResultMatrixInnerInner(value: object): value is MatrixAnalysisResultMatrixInnerInner {
    return true;
}

export function MatrixAnalysisResultMatrixInnerInnerFromJSON(json: any): MatrixAnalysisResultMatrixInnerInner {
    return MatrixAnalysisResultMatrixInnerInnerFromJSONTyped(json, false);
}

export function MatrixAnalysisResultMatrixInnerInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatrixAnalysisResultMatrixInnerInner {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['assetId'] == null ? undefined : json['assetId'],
        'scenarioId': json['scenarioId'] == null ? undefined : json['scenarioId'],
        'impact': json['impact'] == null ? undefined : json['impact'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function MatrixAnalysisResultMatrixInnerInnerToJSON(json: any): MatrixAnalysisResultMatrixInnerInner {
    return MatrixAnalysisResultMatrixInnerInnerToJSONTyped(json, false);
}

export function MatrixAnalysisResultMatrixInnerInnerToJSONTyped(value?: MatrixAnalysisResultMatrixInnerInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assetId': value['assetId'],
        'scenarioId': value['scenarioId'],
        'impact': value['impact'],
        'confidence': value['confidence'],
        'details': value['details'],
    };
}

