/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatrixPost202Response
 */
export interface MatrixPost202Response {
    /**
     * 
     * @type {string}
     * @memberof MatrixPost202Response
     */
    jobId?: string;
}

/**
 * Check if a given object implements the MatrixPost202Response interface.
 */
export function instanceOfMatrixPost202Response(value: object): value is MatrixPost202Response {
    return true;
}

export function MatrixPost202ResponseFromJSON(json: any): MatrixPost202Response {
    return MatrixPost202ResponseFromJSONTyped(json, false);
}

export function MatrixPost202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatrixPost202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
    };
}

export function MatrixPost202ResponseToJSON(json: any): MatrixPost202Response {
    return MatrixPost202ResponseToJSONTyped(json, false);
}

export function MatrixPost202ResponseToJSONTyped(value?: MatrixPost202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
    };
}

