/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatrixAnalysisResultMatrixInnerInner } from './MatrixAnalysisResultMatrixInnerInner';
import {
    MatrixAnalysisResultMatrixInnerInnerFromJSON,
    MatrixAnalysisResultMatrixInnerInnerFromJSONTyped,
    MatrixAnalysisResultMatrixInnerInnerToJSON,
    MatrixAnalysisResultMatrixInnerInnerToJSONTyped,
} from './MatrixAnalysisResultMatrixInnerInner';
import type { MatrixAnalysisResultMetadata } from './MatrixAnalysisResultMetadata';
import {
    MatrixAnalysisResultMetadataFromJSON,
    MatrixAnalysisResultMetadataFromJSONTyped,
    MatrixAnalysisResultMetadataToJSON,
    MatrixAnalysisResultMetadataToJSONTyped,
} from './MatrixAnalysisResultMetadata';

/**
 * 
 * @export
 * @interface MatrixAnalysisResult
 */
export interface MatrixAnalysisResult {
    /**
     * 
     * @type {string}
     * @memberof MatrixAnalysisResult
     */
    id: string;
    /**
     * 
     * @type {Array<Array<MatrixAnalysisResultMatrixInnerInner>>}
     * @memberof MatrixAnalysisResult
     */
    matrix: Array<Array<MatrixAnalysisResultMatrixInnerInner>>;
    /**
     * 
     * @type {MatrixAnalysisResultMetadata}
     * @memberof MatrixAnalysisResult
     */
    metadata?: MatrixAnalysisResultMetadata;
}

/**
 * Check if a given object implements the MatrixAnalysisResult interface.
 */
export function instanceOfMatrixAnalysisResult(value: object): value is MatrixAnalysisResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('matrix' in value) || value['matrix'] === undefined) return false;
    return true;
}

export function MatrixAnalysisResultFromJSON(json: any): MatrixAnalysisResult {
    return MatrixAnalysisResultFromJSONTyped(json, false);
}

export function MatrixAnalysisResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatrixAnalysisResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'matrix': json['matrix'],
        'metadata': json['metadata'] == null ? undefined : MatrixAnalysisResultMetadataFromJSON(json['metadata']),
    };
}

export function MatrixAnalysisResultToJSON(json: any): MatrixAnalysisResult {
    return MatrixAnalysisResultToJSONTyped(json, false);
}

export function MatrixAnalysisResultToJSONTyped(value?: MatrixAnalysisResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'matrix': value['matrix'],
        'metadata': MatrixAnalysisResultMetadataToJSON(value['metadata']),
    };
}

