/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThemeTemplate } from './ThemeTemplate';
import {
    ThemeTemplateFromJSON,
    ThemeTemplateFromJSONTyped,
    ThemeTemplateToJSON,
    ThemeTemplateToJSONTyped,
} from './ThemeTemplate';

/**
 * 
 * @export
 * @interface PaginatedThemeTemplates
 */
export interface PaginatedThemeTemplates {
    /**
     * 
     * @type {Array<ThemeTemplate>}
     * @memberof PaginatedThemeTemplates
     */
    items?: Array<ThemeTemplate>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedThemeTemplates
     */
    total?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedThemeTemplates
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the PaginatedThemeTemplates interface.
 */
export function instanceOfPaginatedThemeTemplates(value: object): value is PaginatedThemeTemplates {
    return true;
}

export function PaginatedThemeTemplatesFromJSON(json: any): PaginatedThemeTemplates {
    return PaginatedThemeTemplatesFromJSONTyped(json, false);
}

export function PaginatedThemeTemplatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedThemeTemplates {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ThemeTemplateFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function PaginatedThemeTemplatesToJSON(json: any): PaginatedThemeTemplates {
    return PaginatedThemeTemplatesToJSONTyped(json, false);
}

export function PaginatedThemeTemplatesToJSONTyped(value?: PaginatedThemeTemplates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ThemeTemplateToJSON)),
        'total': value['total'],
        'hasMore': value['hasMore'],
    };
}

