/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';

/**
 * 
 * @export
 * @interface PaginatedAssets
 */
export interface PaginatedAssets {
    /**
     * 
     * @type {Array<Asset>}
     * @memberof PaginatedAssets
     */
    items?: Array<Asset>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedAssets
     */
    total?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedAssets
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the PaginatedAssets interface.
 */
export function instanceOfPaginatedAssets(value: object): value is PaginatedAssets {
    return true;
}

export function PaginatedAssetsFromJSON(json: any): PaginatedAssets {
    return PaginatedAssetsFromJSONTyped(json, false);
}

export function PaginatedAssetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAssets {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(AssetFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function PaginatedAssetsToJSON(json: any): PaginatedAssets {
    return PaginatedAssetsToJSONTyped(json, false);
}

export function PaginatedAssetsToJSONTyped(value?: PaginatedAssets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(AssetToJSON)),
        'total': value['total'],
        'hasMore': value['hasMore'],
    };
}

