/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
    PaginationInfoToJSONTyped,
} from './PaginationInfo';
import type { Scenario } from './Scenario';
import {
    ScenarioFromJSON,
    ScenarioFromJSONTyped,
    ScenarioToJSON,
    ScenarioToJSONTyped,
} from './Scenario';

/**
 * 
 * @export
 * @interface PaginatedScenarios
 */
export interface PaginatedScenarios {
    /**
     * 
     * @type {Array<Scenario>}
     * @memberof PaginatedScenarios
     */
    data: Array<Scenario>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof PaginatedScenarios
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the PaginatedScenarios interface.
 */
export function instanceOfPaginatedScenarios(value: object): value is PaginatedScenarios {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedScenariosFromJSON(json: any): PaginatedScenarios {
    return PaginatedScenariosFromJSONTyped(json, false);
}

export function PaginatedScenariosFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedScenarios {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ScenarioFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function PaginatedScenariosToJSON(json: any): PaginatedScenarios {
    return PaginatedScenariosToJSONTyped(json, false);
}

export function PaginatedScenariosToJSONTyped(value?: PaginatedScenarios | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ScenarioToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

