/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Scenario } from './Scenario';
import {
    ScenarioFromJSON,
    ScenarioFromJSONTyped,
    ScenarioToJSON,
    ScenarioToJSONTyped,
} from './Scenario';

/**
 * 
 * @export
 * @interface PaginatedScenarios
 */
export interface PaginatedScenarios {
    /**
     * 
     * @type {Array<Scenario>}
     * @memberof PaginatedScenarios
     */
    items?: Array<Scenario>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedScenarios
     */
    total?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedScenarios
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the PaginatedScenarios interface.
 */
export function instanceOfPaginatedScenarios(value: object): value is PaginatedScenarios {
    return true;
}

export function PaginatedScenariosFromJSON(json: any): PaginatedScenarios {
    return PaginatedScenariosFromJSONTyped(json, false);
}

export function PaginatedScenariosFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedScenarios {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ScenarioFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function PaginatedScenariosToJSON(json: any): PaginatedScenarios {
    return PaginatedScenariosToJSONTyped(json, false);
}

export function PaginatedScenariosToJSONTyped(value?: PaginatedScenarios | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ScenarioToJSON)),
        'total': value['total'],
        'hasMore': value['hasMore'],
    };
}

