/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationInfo } from './PaginationInfo';
import {
    PaginationInfoFromJSON,
    PaginationInfoFromJSONTyped,
    PaginationInfoToJSON,
    PaginationInfoToJSONTyped,
} from './PaginationInfo';
import type { ThemeTemplate } from './ThemeTemplate';
import {
    ThemeTemplateFromJSON,
    ThemeTemplateFromJSONTyped,
    ThemeTemplateToJSON,
    ThemeTemplateToJSONTyped,
} from './ThemeTemplate';

/**
 * 
 * @export
 * @interface PaginatedThemeTemplates
 */
export interface PaginatedThemeTemplates {
    /**
     * 
     * @type {Array<ThemeTemplate>}
     * @memberof PaginatedThemeTemplates
     */
    data: Array<ThemeTemplate>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof PaginatedThemeTemplates
     */
    pagination: PaginationInfo;
}

/**
 * Check if a given object implements the PaginatedThemeTemplates interface.
 */
export function instanceOfPaginatedThemeTemplates(value: object): value is PaginatedThemeTemplates {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedThemeTemplatesFromJSON(json: any): PaginatedThemeTemplates {
    return PaginatedThemeTemplatesFromJSONTyped(json, false);
}

export function PaginatedThemeTemplatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedThemeTemplates {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ThemeTemplateFromJSON)),
        'pagination': PaginationInfoFromJSON(json['pagination']),
    };
}

export function PaginatedThemeTemplatesToJSON(json: any): PaginatedThemeTemplates {
    return PaginatedThemeTemplatesToJSONTyped(json, false);
}

export function PaginatedThemeTemplatesToJSONTyped(value?: PaginatedThemeTemplates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ThemeTemplateToJSON)),
        'pagination': PaginationInfoToJSON(value['pagination']),
    };
}

