/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Scenario
 */
export interface Scenario {
    /**
     * 
     * @type {string}
     * @memberof Scenario
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Scenario
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Scenario
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    probability?: number;
}

/**
 * Check if a given object implements the Scenario interface.
 */
export function instanceOfScenario(value: object): value is Scenario {
    return true;
}

export function ScenarioFromJSON(json: any): Scenario {
    return ScenarioFromJSONTyped(json, false);
}

export function ScenarioFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scenario {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'probability': json['probability'] == null ? undefined : json['probability'],
    };
}

export function ScenarioToJSON(json: any): Scenario {
    return ScenarioToJSONTyped(json, false);
}

export function ScenarioToJSONTyped(value?: Scenario | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'probability': value['probability'],
    };
}

