/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScenarioUpdate
 */
export interface ScenarioUpdate {
    /**
     * 
     * @type {string}
     * @memberof ScenarioUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ScenarioUpdate
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof ScenarioUpdate
     */
    parameters?: object;
}

/**
 * Check if a given object implements the ScenarioUpdate interface.
 */
export function instanceOfScenarioUpdate(value: object): value is ScenarioUpdate {
    return true;
}

export function ScenarioUpdateFromJSON(json: any): ScenarioUpdate {
    return ScenarioUpdateFromJSONTyped(json, false);
}

export function ScenarioUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScenarioUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function ScenarioUpdateToJSON(json: any): ScenarioUpdate {
    return ScenarioUpdateToJSONTyped(json, false);
}

export function ScenarioUpdateToJSONTyped(value?: ScenarioUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
    };
}

