/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Scenario
 */
export interface Scenario {
    /**
     * 
     * @type {string}
     * @memberof Scenario
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Scenario
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Scenario
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof Scenario
     */
    parameters?: object;
    /**
     * 
     * @type {Date}
     * @memberof Scenario
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Scenario
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Scenario interface.
 */
export function instanceOfScenario(value: object): value is Scenario {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ScenarioFromJSON(json: any): Scenario {
    return ScenarioFromJSONTyped(json, false);
}

export function ScenarioFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scenario {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ScenarioToJSON(json: any): Scenario {
    return ScenarioToJSONTyped(json, false);
}

export function ScenarioToJSONTyped(value?: Scenario | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

