/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScenarioCreate
 */
export interface ScenarioCreate {
    /**
     * 
     * @type {string}
     * @memberof ScenarioCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ScenarioCreate
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ScenarioCreate
     */
    probability?: number;
}

/**
 * Check if a given object implements the ScenarioCreate interface.
 */
export function instanceOfScenarioCreate(value: object): value is ScenarioCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ScenarioCreateFromJSON(json: any): ScenarioCreate {
    return ScenarioCreateFromJSONTyped(json, false);
}

export function ScenarioCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScenarioCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'probability': json['probability'] == null ? undefined : json['probability'],
    };
}

export function ScenarioCreateToJSON(json: any): ScenarioCreate {
    return ScenarioCreateToJSONTyped(json, false);
}

export function ScenarioCreateToJSONTyped(value?: ScenarioCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'probability': value['probability'],
    };
}

