/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeCreate
 */
export interface ThemeCreate {
    /**
     * 
     * @type {string}
     * @memberof ThemeCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeCreate
     */
    description?: string;
}

/**
 * Check if a given object implements the ThemeCreate interface.
 */
export function instanceOfThemeCreate(value: object): value is ThemeCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ThemeCreateFromJSON(json: any): ThemeCreate {
    return ThemeCreateFromJSONTyped(json, false);
}

export function ThemeCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ThemeCreateToJSON(json: any): ThemeCreate {
    return ThemeCreateToJSONTyped(json, false);
}

export function ThemeCreateToJSONTyped(value?: ThemeCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

