/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeTemplate
 */
export interface ThemeTemplate {
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplate
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplate
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ThemeTemplate
     */
    isPublic?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ThemeTemplate
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ThemeTemplate
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ThemeTemplate interface.
 */
export function instanceOfThemeTemplate(value: object): value is ThemeTemplate {
    return true;
}

export function ThemeTemplateFromJSON(json: any): ThemeTemplate {
    return ThemeTemplateFromJSONTyped(json, false);
}

export function ThemeTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ThemeTemplateToJSON(json: any): ThemeTemplate {
    return ThemeTemplateToJSONTyped(json, false);
}

export function ThemeTemplateToJSONTyped(value?: ThemeTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerId': value['ownerId'],
        'name': value['name'],
        'description': value['description'],
        'isPublic': value['isPublic'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

