/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Theme
 */
export interface Theme {
    /**
     * 
     * @type {string}
     * @memberof Theme
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Theme
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Theme
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Theme
     */
    assetId: string;
    /**
     * 
     * @type {Date}
     * @memberof Theme
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Theme
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Theme interface.
 */
export function instanceOfTheme(value: object): value is Theme {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('assetId' in value) || value['assetId'] === undefined) return false;
    return true;
}

export function ThemeFromJSON(json: any): Theme {
    return ThemeFromJSONTyped(json, false);
}

export function ThemeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Theme {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'assetId': json['assetId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ThemeToJSON(json: any): Theme {
    return ThemeToJSONTyped(json, false);
}

export function ThemeToJSONTyped(value?: Theme | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'assetId': value['assetId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

