/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeTemplateClone
 */
export interface ThemeTemplateClone {
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplateClone
     */
    assetId: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplateClone
     */
    name?: string;
}

/**
 * Check if a given object implements the ThemeTemplateClone interface.
 */
export function instanceOfThemeTemplateClone(value: object): value is ThemeTemplateClone {
    if (!('assetId' in value) || value['assetId'] === undefined) return false;
    return true;
}

export function ThemeTemplateCloneFromJSON(json: any): ThemeTemplateClone {
    return ThemeTemplateCloneFromJSONTyped(json, false);
}

export function ThemeTemplateCloneFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeTemplateClone {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['assetId'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ThemeTemplateCloneToJSON(json: any): ThemeTemplateClone {
    return ThemeTemplateCloneToJSONTyped(json, false);
}

export function ThemeTemplateCloneToJSONTyped(value?: ThemeTemplateClone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assetId': value['assetId'],
        'name': value['name'],
    };
}

