/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeTemplatesGet400Response
 */
export interface ThemeTemplatesGet400Response {
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplatesGet400Response
     */
    error?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ThemeTemplatesGet400Response
     */
    details?: Array<string>;
}

/**
 * Check if a given object implements the ThemeTemplatesGet400Response interface.
 */
export function instanceOfThemeTemplatesGet400Response(value: object): value is ThemeTemplatesGet400Response {
    return true;
}

export function ThemeTemplatesGet400ResponseFromJSON(json: any): ThemeTemplatesGet400Response {
    return ThemeTemplatesGet400ResponseFromJSONTyped(json, false);
}

export function ThemeTemplatesGet400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeTemplatesGet400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ThemeTemplatesGet400ResponseToJSON(json: any): ThemeTemplatesGet400Response {
    return ThemeTemplatesGet400ResponseToJSONTyped(json, false);
}

export function ThemeTemplatesGet400ResponseToJSONTyped(value?: ThemeTemplatesGet400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'details': value['details'],
    };
}

