/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeTemplatesGet429Response
 */
export interface ThemeTemplatesGet429Response {
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplatesGet429Response
     */
    error?: string;
}

/**
 * Check if a given object implements the ThemeTemplatesGet429Response interface.
 */
export function instanceOfThemeTemplatesGet429Response(value: object): value is ThemeTemplatesGet429Response {
    return true;
}

export function ThemeTemplatesGet429ResponseFromJSON(json: any): ThemeTemplatesGet429Response {
    return ThemeTemplatesGet429ResponseFromJSONTyped(json, false);
}

export function ThemeTemplatesGet429ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeTemplatesGet429Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ThemeTemplatesGet429ResponseToJSON(json: any): ThemeTemplatesGet429Response {
    return ThemeTemplatesGet429ResponseToJSONTyped(json, false);
}

export function ThemeTemplatesGet429ResponseToJSONTyped(value?: ThemeTemplatesGet429Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

