/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeTemplateUpdate
 */
export interface ThemeTemplateUpdate {
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplateUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplateUpdate
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof ThemeTemplateUpdate
     */
    template?: object;
    /**
     * 
     * @type {boolean}
     * @memberof ThemeTemplateUpdate
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the ThemeTemplateUpdate interface.
 */
export function instanceOfThemeTemplateUpdate(value: object): value is ThemeTemplateUpdate {
    return true;
}

export function ThemeTemplateUpdateFromJSON(json: any): ThemeTemplateUpdate {
    return ThemeTemplateUpdateFromJSONTyped(json, false);
}

export function ThemeTemplateUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeTemplateUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'template': json['template'] == null ? undefined : json['template'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

export function ThemeTemplateUpdateToJSON(json: any): ThemeTemplateUpdate {
    return ThemeTemplateUpdateToJSONTyped(json, false);
}

export function ThemeTemplateUpdateToJSONTyped(value?: ThemeTemplateUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'template': value['template'],
        'isPublic': value['isPublic'],
    };
}

