/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeUpdate
 */
export interface ThemeUpdate {
    /**
     * 
     * @type {string}
     * @memberof ThemeUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeUpdate
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeUpdate
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof ThemeUpdate
     */
    manualValue?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ThemeUpdate
     */
    useManualValue?: boolean;
}

/**
 * Check if a given object implements the ThemeUpdate interface.
 */
export function instanceOfThemeUpdate(value: object): value is ThemeUpdate {
    return true;
}

export function ThemeUpdateFromJSON(json: any): ThemeUpdate {
    return ThemeUpdateFromJSONTyped(json, false);
}

export function ThemeUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category'] == null ? undefined : json['category'],
        'manualValue': json['manualValue'] == null ? undefined : json['manualValue'],
        'useManualValue': json['useManualValue'] == null ? undefined : json['useManualValue'],
    };
}

export function ThemeUpdateToJSON(json: any): ThemeUpdate {
    return ThemeUpdateToJSONTyped(json, false);
}

export function ThemeUpdateToJSONTyped(value?: ThemeUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'category': value['category'],
        'manualValue': value['manualValue'],
        'useManualValue': value['useManualValue'],
    };
}

