/* tslint:disable */
/* eslint-disable */
/**
 * Finex Bot API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeTemplateCreate
 */
export interface ThemeTemplateCreate {
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplateCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ThemeTemplateCreate
     */
    description?: string;
    /**
     * ID of the theme to use as template
     * @type {string}
     * @memberof ThemeTemplateCreate
     */
    themeId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ThemeTemplateCreate
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the ThemeTemplateCreate interface.
 */
export function instanceOfThemeTemplateCreate(value: object): value is ThemeTemplateCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('themeId' in value) || value['themeId'] === undefined) return false;
    return true;
}

export function ThemeTemplateCreateFromJSON(json: any): ThemeTemplateCreate {
    return ThemeTemplateCreateFromJSONTyped(json, false);
}

export function ThemeTemplateCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeTemplateCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'themeId': json['themeId'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

export function ThemeTemplateCreateToJSON(json: any): ThemeTemplateCreate {
    return ThemeTemplateCreateToJSONTyped(json, false);
}

export function ThemeTemplateCreateToJSONTyped(value?: ThemeTemplateCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'themeId': value['themeId'],
        'isPublic': value['isPublic'],
    };
}

